# This is a basic workflow to help you get started with Actions

name: NewRom

# Controls when the workflow will run
on: 
    push:
       branches:
          - main
    pull_request:
       branches:
          - main
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Start
      uses: actions/checkout@v3
      with:
        # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        persist-credentials: false 
        # otherwise, there would be errors pushing refs to the destination repository.
        fetch-depth: 0 
    - name: Clone source code
      env:
        PORT0: 60002
        PORT1: 60003
      run: |
        git clone --depth=1 https://github.com/HeroPoter/padavan2.git /opt/modify
        cd /opt/modify
        chmod +x modify.sh
        chmod +x mksquashfs
        chmod +x padjffs2
        chmod +x unsquashfs   
        sh modify.sh e newrom60.trx
        #PORT0=60000
        #PORT1=60001
        sudo sed -i "29c remote_port = $PORT0" /opt/modify/squashfs-root/sbin/frp_script.sh
        sudo sed -i "36c remote_port = $PORT1" /opt/modify/squashfs-root/sbin/frp_script.sh
        mkdir -p /opt/modify/images/
        sh modify.sh c newrom$PORT0.trx
        sudo mv -f newrom$PORT0.trx /opt/modify/images/
        sudo mv -f /opt/modify/squashfs-root/sbin/frp_script.sh /opt/modify/images/
    - name: Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/modify/images
