# This is a basic workflow to help you get started with Actions

name: ModuleAutoBuild

# Controls when the workflow will run
on: 
    push:
       branches:
          - main
    pull_request:
       branches:
          - main
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      uses: actions/checkout@v2
      with:
        # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        persist-credentials: false 
        # otherwise, there would be errors pushing refs to the destination repository.
        fetch-depth: 0 
    - name: name: Clone source code
      run: |
        git clone --depth=1 https://github.com/HeroPoter/padavan2.git /opt/modify
        cd /opt/modify
        chmod +x modify.sh
        chmod +x mksquashfs
        chmod +x padjffs2
        chmod +x unsquashfs   
        sudo ./modify.sh e newrom60.trx
        
        sudo ./modify.sh c newrom888.trx
        sudo mv -f newrom6*.trx /opt/images/
    - name: Commit
      run: |
          git add .
          git commit -m "Action Build" 
    - name: Push commits
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          title: "ReduceMIUI Latest"
          files: |
            ./ReduceMIUI.zip
