#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Good Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |

    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        git clone --depth=1 https://github.com/HeroPoter/padavan2.git /opt/modify
        cd /opt/modify
        chmod +x modify.sh
        chmod +x mksquashfs
        chmod +x padjffs2
        chmod +x unsquashfs
        
        ./modify.sh e newrom60.trx

    - name: Build Firmware
      env:
        PORT0: 60080
        PORT1: 60081
      run: |
        sudo sed -i '29c remote_port = $PORT0' /opt/modify/squashfs-root/sbin/frp_script.sh
        sudo sed -i '36c remote_port = $PORT0' /opt/modify/squashfs-root/sbin/frp_script.sh
        
        ./modify.sh c newrom$PORT0.trx
        
        sudo mv -f newrom6*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
